# Generated by Django 3.2.12 on 2023-09-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='is_verirified_email',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verirified_email',
            field=models.BooleanField(default=False),
        ),
    ]
